### An end to end scikit learn workflow

In [20]:
import pandas as pd
hd = pd.read_csv('Data\heartdisease.csv')
hd

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [21]:
x = hd.drop('target', axis=1)
y = hd['target']

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [27]:
clf = RandomForestClassifier()
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [28]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [32]:
clf.fit(x_train,y_train);

In [39]:
x_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
289,55,0,0,128,205,0,2,130,1,2.0,1,1,3
225,70,1,0,145,174,0,1,125,1,2.6,0,0,3
158,58,1,1,125,220,0,1,144,0,0.4,1,4,3
142,42,0,2,120,209,0,1,173,0,0.0,1,0,2
51,66,1,0,120,302,0,0,151,0,0.4,1,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,66,1,0,160,228,0,0,138,0,2.3,2,0,1
123,54,0,2,108,267,0,0,167,0,0.0,2,0,2
195,59,1,0,170,326,0,0,140,1,3.4,0,0,3
42,45,1,0,104,208,0,0,148,1,3.0,1,0,2
36,54,0,2,135,304,1,1,170,0,0.0,2,0,2

In [40]:
x_test

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
181,65,0,0,150,225,0,0,114,0,1.0,1,3,3
198,62,1,0,120,267,0,1,99,1,1.8,1,2,3
84,42,0,0,102,265,0,0,122,0,0.6,1,0,2
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
200,44,1,0,110,197,0,0,177,0,0.0,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,76,0,2,140,197,0,2,116,0,1.1,1,0,2
96,62,0,0,140,394,0,0,157,0,1.2,1,0,2
244,56,1,0,132,184,0,0,105,1,2.1,1,1,1
171,48,1,1,110,229,0,1,168,0,1.0,0,0,3
100,42,1,3,148,244,0,0,178,0,0.8,2,2,2

In [38]:
import numpy as np

In [36]:
#making a prediction
y_label = clf.predict(np.array([0,2,3,4]))

ValueError: Expected 2D array, got 1D array instead:
array=[0. 2. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [41]:
y_preds = clf.predict(x_test)

In [42]:
y_preds

array([0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1], dtype=int64)

In [43]:
y_test

181    0
198    0
84     1
299    0
200    0
      ..
144    1
96     1
244    0
171    0
100    1
Name: target, Length: 61, dtype: int64

In [48]:
#evaluate the model
clf.score(x_train,y_train)

1.0

In [49]:
clf.score(x_test, y_test)

0.8360655737704918

In [50]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.83      0.77      0.80        26
           1       0.84      0.89      0.86        35

    accuracy                           0.84        61
   macro avg       0.84      0.83      0.83        61
weighted avg       0.84      0.84      0.84        61

In [51]:
confusion_matrix(y_test, y_preds)

array([[20,  6],
       [ 4, 31]], dtype=int64)

In [52]:
accuracy_score(y_test, y_preds)

0.8360655737704918

In [57]:
np.random.seed(111)

for i in range(10,100,10):
    print("Trying model with " + str(i) +" estimators...")
    clf = RandomForestClassifier(n_estimators = i).fit(x_train,y_train)
    print(f"Model accuarcy : {clf.score(x_test,y_test)*100}")
    print("\n")

Trying model with 10 estimators...
Model accuarcy : 81.9672131147541


Trying model with 20 estimators...
Model accuarcy : 86.88524590163934


Trying model with 30 estimators...
Model accuarcy : 88.52459016393442


Trying model with 40 estimators...
Model accuarcy : 83.60655737704919


Trying model with 50 estimators...
Model accuarcy : 85.24590163934425


Trying model with 60 estimators...
Model accuarcy : 86.88524590163934


Trying model with 70 estimators...
Model accuarcy : 83.60655737704919


Trying model with 80 estimators...
Model accuarcy : 83.60655737704919


Trying model with 90 estimators...
Model accuarcy : 86.88524590163934

In [58]:
import pickle

pickle.dump(clf, open("random_forest_model_1.pk1", "wb"))

In [60]:
loaded_model = pickle.load(open("random_forest_model_1.pk1", "rb"))

loaded_model.score(x_test,y_test)

0.8688524590163934